---
name: Feature Request
description: Suggest an idea for this project
title: "[REQ] "
labels: enhancement
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Please describe the feature you would like to see added to the MG SAIC Integration.**

  - type: checkboxes
    id: problem_exists
    attributes:
      label: Is your feature request related to a problem?
      options:
        - label: "Yes"

  - type: textarea
    id: problem
    attributes:
      label: Please describe the problem
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: false
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
